#!/usr/bin/env node
/**
 * scripts/gen-types.mjs
 *
 * Docker-free alternative to `pnpm gen:types`.
 * Introspects the `calcifer` schema via a direct PostgreSQL connection
 * and writes TypeScript types to apps/desktop/src/types/database.types.ts.
 *
 * Usage:
 *   node scripts/gen-types.mjs
 *   # or via package.json script:
 *   pnpm gen:types:no-docker
 *
 * Requirements: pg (installed as dev dep in workspace root)
 */

import pg from "pg";
import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const { Client } = pg;

const DB_URL =
  process.env.DATABASE_URL ??
  "postgres://postgres.cogito-pooler:Cogito-092023@114.67.246.199:5432/postgres";
const SCHEMA = process.env.DB_SCHEMA ?? "calcifer";
const OUT_FILE = join(
  dirname(fileURLToPath(import.meta.url)),
  "../apps/desktop/src/types/database.types.ts"
);

// ── Queries ───────────────────────────────────────────────────────────────────

const TABLES_QUERY = `
  SELECT table_name
  FROM information_schema.tables
  WHERE table_schema = $1
    AND table_type = 'BASE TABLE'
  ORDER BY table_name;
`;

const COLUMNS_QUERY = `
  SELECT
    c.table_name,
    c.column_name,
    c.data_type,
    c.udt_name,
    c.is_nullable,
    c.column_default,
    c.character_maximum_length
  FROM information_schema.columns c
  WHERE c.table_schema = $1
  ORDER BY c.table_name, c.ordinal_position;
`;

const ENUMS_QUERY = `
  SELECT
    t.typname AS enum_name,
    array_agg(e.enumlabel ORDER BY e.enumsortorder) AS values
  FROM pg_type t
  JOIN pg_enum e ON t.oid = e.enumtypid
  JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = $1
  GROUP BY t.typname
  ORDER BY t.typname;
`;

// ── PG type → TS type mapping ─────────────────────────────────────────────────

function pgToTs(dataType, udtName, enumNames) {
  if (enumNames.has(udtName)) return udtName;
  switch (dataType) {
    case "text":
    case "character varying":
    case "character":
    case "uuid":
    case "timestamp with time zone":
    case "timestamp without time zone":
    case "date":
    case "time with time zone":
    case "time without time zone":
    case "inet":
    case "citext":
      return "string";
    case "integer":
    case "smallint":
    case "bigint":
    case "numeric":
    case "real":
    case "double precision":
      return "number";
    case "boolean":
      return "boolean";
    case "jsonb":
    case "json":
      return "Json";
    case "ARRAY":
      return "unknown[]";
    default:
      return "unknown";
  }
}

// ── Code generation ───────────────────────────────────────────────────────────

function generateTypes(tables, columns, enums) {
  const enumNames = new Set(enums.map((e) => e.enum_name));

  // Group columns by table
  const colsByTable = {};
  for (const col of columns) {
    (colsByTable[col.table_name] ??= []).push(col);
  }

  let out = `// This file is auto-generated by scripts/gen-types.mjs
// Do not edit manually — run \`pnpm gen:types:no-docker\` to regenerate.
// Schema: ${SCHEMA} | Generated: ${new Date().toISOString()}

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

`;

  // Enum types
  for (const { enum_name, values } of enums) {
    out += `export type ${enum_name} = ${values.map((v) => `'${v}'`).join(" | ")}\n`;
  }
  if (enums.length) out += "\n";

  // Database interface
  out += `export interface Database {\n  ${SCHEMA}: {\n    Tables: {\n`;

  for (const { table_name } of tables) {
    const cols = colsByTable[table_name] ?? [];
    const rowFields = cols
      .map((c) => {
        const ts = pgToTs(c.data_type, c.udt_name, enumNames);
        const nullable = c.is_nullable === "YES";
        return `          ${c.column_name}: ${ts}${nullable ? " | null" : ""}`;
      })
      .join("\n");

    const insertFields = cols
      .map((c) => {
        const ts = pgToTs(c.data_type, c.udt_name, enumNames);
        const nullable = c.is_nullable === "YES";
        const hasDefault = c.column_default !== null;
        const optional = nullable || hasDefault;
        return `          ${c.column_name}${optional ? "?" : ""}: ${ts}${nullable ? " | null" : ""}`;
      })
      .join("\n");

    out += `      ${table_name}: {\n        Row: {\n${rowFields}\n        }\n        Insert: {\n${insertFields}\n        }\n        Update: {\n${insertFields.replace(/[^?]:/, "?:")}\n        }\n      }\n`;
  }

  if (tables.length === 0) {
    out += `      [_ in never]: never\n`;
  }

  out += `    }\n    Views: {\n      [_ in never]: never\n    }\n    Enums: {\n`;

  for (const { enum_name, values } of enums) {
    out += `      ${enum_name}: ${values.map((v) => `'${v}'`).join(" | ")}\n`;
  }
  if (enums.length === 0) out += `      [_ in never]: never\n`;

  out += `    }\n  }\n}\n`;

  return out;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const client = new Client({ connectionString: DB_URL });
  await client.connect();

  try {
    const tablesRes = await client.query(TABLES_QUERY, [SCHEMA]);
    const columnsRes = await client.query(COLUMNS_QUERY, [SCHEMA]);
    const enumsRes = await client.query(ENUMS_QUERY, [SCHEMA]);

    const code = generateTypes(tablesRes.rows, columnsRes.rows, enumsRes.rows);

    mkdirSync(dirname(OUT_FILE), { recursive: true });
    writeFileSync(OUT_FILE, code, "utf-8");

    console.log(`✅  types written → ${OUT_FILE}`);
    console.log(
      `   tables: ${tablesRes.rows.length} | enums: ${enumsRes.rows.length}`
    );
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error("❌", err.message);
  process.exit(1);
});
