// This file is auto-generated by scripts/gen-types.mjs
// Do not edit manually — run `pnpm gen:types:no-docker` to regenerate.
// Schema: calcifer | Generated: 2026-05-26T03:33:53.359Z

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  calcifer: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
